// PennyPilot/frontend/src/lib/components/ui/Spinner.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';

  let { class: className = '' }: { class?: string } = $props();
</script>

<div
  class={cn(
    'inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent',
    className
  )}
  role="status"
  aria-label="Loading"
></div>

// Weathervane/frontend/src/components/ui/Spinner.vue
<script setup lang="ts">
import { Loader2 } from "lucide-vue-next";
import type { HTMLAttributes } from "vue";

import { cn } from "@/lib/utils/cn";

const props = defineProps<{ class?: HTMLAttributes["class"]; label?: string }>();
</script>

<template>
  <span role="status" :aria-label="props.label ?? 'Loading'" class="inline-flex">
    <Loader2 :class="cn('h-4 w-4 animate-spin', props.class)" aria-hidden="true" />
  </span>
</template>
