// SkyScout/frontend/src/components/common/EmptyState.tsx
import type { LucideIcon } from "lucide-react";
import { Inbox } from "lucide-react";
import type { ReactNode } from "react";

import { cn } from "@/lib/utils";

interface EmptyStateProps {
  icon?: LucideIcon;
  title: string;
  description?: string;
  action?: ReactNode;
  className?: string;
}

export function EmptyState({ icon: Icon = Inbox, title, description, action, className }: EmptyStateProps) {
  return (
    <div
      className={cn(
        "flex flex-col items-center justify-center rounded-lg border border-dashed p-10 text-center",
        className,
      )}
    >
      <Icon className="mb-4 h-10 w-10 text-muted-foreground" aria-hidden />
      <h3 className="text-base font-semibold">{title}</h3>
      {description && <p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// Weathervane/frontend/src/components/common/EmptyState.vue
<script setup lang="ts">
import { Inbox, type LucideIcon } from "lucide-vue-next";

defineProps<{ title: string; description?: string; icon?: LucideIcon }>();
</script>

<template>
  <div
    class="flex flex-col items-center justify-center gap-3 rounded-xl border border-dashed p-10 text-center"
  >
    <component :is="icon ?? Inbox" class="h-8 w-8 text-muted-foreground" aria-hidden="true" />
    <div class="space-y-1">
      <p class="font-medium">{{ title }}</p>
      <p v-if="description" class="text-sm text-muted-foreground">{{ description }}</p>
    </div>
    <slot />
  </div>
</template>
