// pennypilot/frontend/src/App.svelte
<script>
  import { API_URL, setBudget, checkExpense, getRemaining } from "./api.js";

  let total = 5000;
  let expense = 1200;
  let status = null; // { totalBudget, spent, remaining }
  let lastResult = null; // { approved, remaining, spent }
  let error = null;

  async function doSet() {
    error = null;
    try {
      status = await setBudget(total);
      lastResult = null;
    } catch (e) { error = e.message; }
  }

  async function doCheck() {
    error = null;
    try {
      lastResult = await checkExpense(expense);
      status = await getRemaining();
    } catch (e) { error = e.message; }
  }

  async function doRefresh() {
    error = null;
    try { status = await getRemaining(); } catch (e) { error = e.message; }
  }
</script>

<main>
  <h1>💰 PennyPilot</h1>
  <p class="sub">Keep your trip on budget (stateful) — talks only to its own backend at <code>{API_URL}</code></p>

  <section>
    <label>Total budget <input type="number" bind:value={total} /></label>
    <button on:click={doSet}>Set budget</button>
  </section>

  <section>
    <label>Expense <input type="number" bind:value={expense} /></label>
    <button on:click={doCheck}>Check expense</button>
    <button on:click={doRefresh}>Refresh remaining</button>
  </section>

  {#if error}<p class="error">Error: {error}</p>{/if}

  {#if lastResult}
    <p class="result {lastResult.approved ? 'ok' : 'bad'}">
      Expense {lastResult.approved ? "APPROVED ✅" : "REJECTED ❌"} —
      remaining ${lastResult.remaining.toFixed(2)}
    </p>
  {/if}

  {#if status}
    <div class="card">
      <div>Total: <strong>${status.totalBudget.toFixed(2)}</strong></div>
      <div>Spent: <strong>${status.spent.toFixed(2)}</strong></div>
      <div>Remaining: <strong>${status.remaining.toFixed(2)}</strong></div>
    </div>
  {:else}
    <p>Set a budget to begin.</p>
  {/if}
</main>

<style>
  main { font-family: system-ui, sans-serif; max-width: 560px; margin: 2rem auto; padding: 0 1rem; }
  .sub { color: #555; }
  section { display: flex; gap: 0.5rem; align-items: center; margin: 0.75rem 0; flex-wrap: wrap; }
  input { width: 120px; }
  .card { border: 1px solid #ddd; border-radius: 8px; padding: 0.75rem 1rem; display: grid; gap: 4px; }
  .error { color: #b00020; }
  .result.ok { color: #0a7d28; }
  .result.bad { color: #b00020; }
</style>

// Weathervane/frontend/src/App.vue
<script setup>
import { ref } from "vue";
import { API_URL, getForecast } from "./api.js";

const city = ref("London");
const days = ref(5);
const results = ref([]);
const error = ref(null);
const loading = ref(false);

async function search() {
  loading.value = true;
  error.value = null;
  try {
    results.value = await getForecast(city.value, Number(days.value));
  } catch (e) {
    error.value = e.message;
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <main>
    <h1>🌤️ Weathervane</h1>
    <p class="sub">See the forecast for your trip — talks only to its own backend at <code>{{ API_URL }}</code></p>

    <form @submit.prevent="search">
      <label>City <input v-model="city" placeholder="London" /></label>
      <label>Days <input v-model="days" type="number" min="1" max="5" style="width:70px" /></label>
      <button type="submit" :disabled="loading">{{ loading ? "Loading…" : "Get forecast" }}</button>
    </form>

    <p v-if="error" class="error">Error: {{ error }}</p>

    <ul>
      <li v-for="d in results" :key="d.date" class="card">
        <strong>{{ d.date }}</strong> — {{ d.condition }}
        <span class="meta">high {{ d.high }}°C · low {{ d.low }}°C</span>
      </li>
    </ul>
    <p v-if="!loading && !error && results.length === 0">No forecast yet — run a search.</p>
  </main>
</template>

<style scoped>
main { font-family: system-ui, sans-serif; max-width: 560px; margin: 2rem auto; padding: 0 1rem; }
.sub { color: #555; }
form { display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; margin: 1rem 0; }
ul { list-style: none; padding: 0; display: grid; gap: 0.5rem; }
.card { border: 1px solid #ddd; border-radius: 8px; padding: 0.6rem 1rem; }
.meta { color: #666; font-size: 0.9rem; margin-left: 8px; }
.error { color: #b00020; }
</style>
