// SkyScout/frontend/src/components/common/EmptyState.tsx
import type { LucideIcon } from "lucide-react";
import { Inbox } from "lucide-react";
import type { ReactNode } from "react";

import { cn } from "@/lib/utils";

interface EmptyStateProps {
  icon?: LucideIcon;
  title: string;
  description?: string;
  action?: ReactNode;
  className?: string;
}

export function EmptyState({ icon: Icon = Inbox, title, description, action, className }: EmptyStateProps) {
  return (
    <div
      className={cn(
        "flex flex-col items-center justify-center rounded-lg border border-dashed p-10 text-center",
        className,
      )}
    >
      <Icon className="mb-4 h-10 w-10 text-muted-foreground" aria-hidden />
      <h3 className="text-base font-semibold">{title}</h3>
      {description && <p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// TripWeaver/frontend/src/components/common/EmptyState.tsx
import { Show, type JSX } from 'solid-js';

export function EmptyState(props: {
  title: string;
  message?: string;
  icon?: JSX.Element;
  action?: JSX.Element;
}) {
  return (
    <div class="flex flex-col items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center">
      <Show when={props.icon}>{props.icon}</Show>
      <h3 class="text-lg font-semibold text-slate-800">{props.title}</h3>
      <Show when={props.message}>
        <p class="max-w-sm text-sm text-slate-500">{props.message}</p>
      </Show>
      <Show when={props.action}>{props.action}</Show>
    </div>
  );
}
