// SkyScout/frontend/src/components/common/ErrorState.tsx
import { AlertTriangle } from "lucide-react";

import { Button } from "@/components/ui/button";
import { ApiError } from "@/lib/ApiError";
import { cn } from "@/lib/utils";

interface ErrorStateProps {
  error?: unknown;
  title?: string;
  onRetry?: () => void;
  className?: string;
}

function messageFor(error: unknown): string {
  if (error instanceof ApiError) return error.message;
  if (error instanceof Error) return error.message;
  return "Something went wrong. Please try again.";
}

export function ErrorState({ error, title = "Something went wrong", onRetry, className }: ErrorStateProps) {
  const requestId = error instanceof ApiError ? error.requestId : undefined;
  return (
    <div
      role="alert"
      className={cn(
        "flex flex-col items-center justify-center rounded-lg border border-destructive/30 bg-destructive/5 p-10 text-center",
        className,
      )}
    >
      <AlertTriangle className="mb-4 h-10 w-10 text-destructive" aria-hidden />
      <h3 className="text-base font-semibold">{title}</h3>
      <p className="mt-1 max-w-sm text-sm text-muted-foreground">{messageFor(error)}</p>
      {requestId && <p className="mt-1 text-xs text-muted-foreground/70">Reference: {requestId}</p>}
      {onRetry && (
        <Button variant="outline" className="mt-4" onClick={onRetry}>
          Try again
        </Button>
      )}
    </div>
  );
}

// TripWeaver/frontend/src/components/common/ErrorState.tsx
import { Show } from 'solid-js';
import { TriangleAlert } from 'lucide-solid';
import { Button } from '@/components/ui/Button';

export function ErrorState(props: { message?: string; onRetry?: () => void }) {
  return (
    <div class="flex flex-col items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-12 text-center">
      <TriangleAlert size={32} class="text-over" aria-hidden="true" />
      <h3 class="text-lg font-semibold text-slate-800">Something went wrong</h3>
      <p class="max-w-sm text-sm text-slate-600">
        {props.message ?? 'We could not load this. Please try again.'}
      </p>
      <Show when={props.onRetry}>
        <Button variant="secondary" size="sm" onClick={() => props.onRetry?.()}>
          Retry
        </Button>
      </Show>
    </div>
  );
}
