// SkyScout/frontend/src/components/common/NavBar.tsx
import { LogOut, Menu, Plane, ShieldCheck, Ticket } from "lucide-react";
import { Link, NavLink } from "react-router-dom";

import { ThemeToggle } from "@/components/common/ThemeToggle";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useLogout } from "@/features/auth";
import { useAuth } from "@/hooks/useAuth";
import { cn } from "@/lib/utils";

interface NavItem {
  to: string;
  label: string;
  show: boolean;
}

function useNavItems(): NavItem[] {
  const { isAuthenticated, isAdmin } = useAuth();
  return [
    { to: "/flights", label: "Flights", show: true },
    { to: "/bookings", label: "My Bookings", show: isAuthenticated },
    { to: "/admin/flights", label: "Admin", show: isAdmin },
  ].filter((item) => item.show);
}

function desktopLinkClass({ isActive }: { isActive: boolean }) {
  return cn(
    "text-sm font-medium transition-colors hover:text-foreground",
    isActive ? "text-foreground" : "text-muted-foreground",
  );
}

export function NavBar() {
  const { isAuthenticated, isAdmin, user } = useAuth();
  const items = useNavItems();
  const logout = useLogout();

  return (
    <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-16 items-center justify-between gap-4">
        <div className="flex items-center gap-8">
          <Link to="/flights" className="flex items-center gap-2 font-bold">
            <Plane className="h-5 w-5 text-primary" aria-hidden />
            <span>SkyScout</span>
          </Link>
          <nav className="hidden items-center gap-6 md:flex">
            {items.map((item) => (
              <NavLink key={item.to} to={item.to} className={desktopLinkClass}>
                {item.label}
              </NavLink>
            ))}
          </nav>
        </div>

        <div className="flex items-center gap-2">
          <ThemeToggle />

          <div className="hidden md:block">
            {isAuthenticated ? (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" size="sm" className="max-w-[12rem]">
                    <span className="truncate">{user?.email ?? "Account"}</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-56">
                  <DropdownMenuLabel className="truncate">{user?.email}</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem asChild>
                    <Link to="/bookings">
                      <Ticket className="h-4 w-4" /> My Bookings
                    </Link>
                  </DropdownMenuItem>
                  {isAdmin && (
                    <DropdownMenuItem asChild>
                      <Link to="/admin/flights">
                        <ShieldCheck className="h-4 w-4" /> Admin
                      </Link>
                    </DropdownMenuItem>
                  )}
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={logout}>
                    <LogOut className="h-4 w-4" /> Sign out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <div className="flex items-center gap-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link to="/login">Sign in</Link>
                </Button>
                <Button size="sm" asChild>
                  <Link to="/register">Sign up</Link>
                </Button>
              </div>
            )}
          </div>

          <div className="md:hidden">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" aria-label="Open menu">
                  <Menu className="h-5 w-5" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                {items.map((item) => (
                  <DropdownMenuItem key={item.to} asChild>
                    <Link to={item.to}>{item.label}</Link>
                  </DropdownMenuItem>
                ))}
                <DropdownMenuSeparator />
                {isAuthenticated ? (
                  <>
                    <DropdownMenuLabel className="truncate text-xs font-normal text-muted-foreground">
                      {user?.email}
                    </DropdownMenuLabel>
                    <DropdownMenuItem onClick={logout}>
                      <LogOut className="h-4 w-4" /> Sign out
                    </DropdownMenuItem>
                  </>
                ) : (
                  <>
                    <DropdownMenuItem asChild>
                      <Link to="/login">Sign in</Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link to="/register">Sign up</Link>
                    </DropdownMenuItem>
                  </>
                )}
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
    </header>
  );
}

// TripWeaver/frontend/src/components/common/NavBar.tsx
import { Show } from 'solid-js';
import { A, useNavigate } from '@solidjs/router';
import { useQueryClient } from '@tanstack/solid-query';
import { Plane } from 'lucide-solid';
import { authStore } from '@/lib/stores/auth.store';
import { Button } from '@/components/ui/Button';

const linkClass = 'rounded px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-100';
const activeClass = '!font-semibold !text-brand-700';

export function NavBar() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const logout = () => {
    authStore.clearSession();
    queryClient.clear();
    navigate('/login', { replace: true });
  };

  return (
    <header class="sticky top-0 z-30 border-b border-slate-200 bg-white">
      <div class="mx-auto flex max-w-6xl items-center gap-3 px-4 py-3">
        <A href="/itineraries" class="flex items-center gap-2 font-semibold text-brand-600">
          <Plane size={20} aria-hidden="true" />
          <span>TripWeaver</span>
        </A>
        <nav class="flex flex-1 items-center gap-1">
          <A href="/itineraries" class={linkClass} activeClass={activeClass} end>
            My itineraries
          </A>
          <A href="/itineraries/new" class={linkClass} activeClass={activeClass}>
            New trip
          </A>
          <Show when={authStore.isAdmin()}>
            <A href="/admin" class={linkClass} activeClass={activeClass}>
              Admin
            </A>
          </Show>
        </nav>
        <Show when={authStore.user}>
          {(user) => <span class="hidden text-sm text-slate-500 sm:inline">{user().email}</span>}
        </Show>
        <Button variant="ghost" size="sm" onClick={logout}>
          Sign out
        </Button>
      </div>
    </header>
  );
}
