// PennyPilot/frontend/src/lib/components/common/PageHeader.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    description?: string;
    actions?: Snippet;
  }

  let { title, description, actions }: Props = $props();
</script>

<div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
  <div class="space-y-1">
    <h1 class="text-2xl font-bold tracking-tight">{title}</h1>
    {#if description}<p class="text-sm text-muted-foreground">{description}</p>{/if}
  </div>
  {#if actions}<div class="flex flex-wrap items-center gap-2">{@render actions()}</div>{/if}
</div>

// TripWeaver/frontend/src/components/common/PageHeader.tsx
import { Show, type JSX } from 'solid-js';

export function PageHeader(props: { title: string; subtitle?: string; actions?: JSX.Element }) {
  return (
    <div class="mb-6 flex flex-wrap items-start justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-slate-900">{props.title}</h1>
        <Show when={props.subtitle}>
          <p class="mt-1 text-slate-500">{props.subtitle}</p>
        </Show>
      </div>
      <Show when={props.actions}>{props.actions}</Show>
    </div>
  );
}
