// Weathervane/frontend/src/App.vue
<script setup>
import { ref } from "vue";
import { API_URL, getForecast } from "./api.js";

const city = ref("London");
const days = ref(5);
const results = ref([]);
const error = ref(null);
const loading = ref(false);

async function search() {
  loading.value = true;
  error.value = null;
  try {
    results.value = await getForecast(city.value, Number(days.value));
  } catch (e) {
    error.value = e.message;
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <main>
    <h1>🌤️ Weathervane</h1>
    <p class="sub">See the forecast for your trip — talks only to its own backend at <code>{{ API_URL }}</code></p>

    <form @submit.prevent="search">
      <label>City <input v-model="city" placeholder="London" /></label>
      <label>Days <input v-model="days" type="number" min="1" max="5" style="width:70px" /></label>
      <button type="submit" :disabled="loading">{{ loading ? "Loading…" : "Get forecast" }}</button>
    </form>

    <p v-if="error" class="error">Error: {{ error }}</p>

    <ul>
      <li v-for="d in results" :key="d.date" class="card">
        <strong>{{ d.date }}</strong> — {{ d.condition }}
        <span class="meta">high {{ d.high }}°C · low {{ d.low }}°C</span>
      </li>
    </ul>
    <p v-if="!loading && !error && results.length === 0">No forecast yet — run a search.</p>
  </main>
</template>

<style scoped>
main { font-family: system-ui, sans-serif; max-width: 560px; margin: 2rem auto; padding: 0 1rem; }
.sub { color: #555; }
form { display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; margin: 1rem 0; }
ul { list-style: none; padding: 0; display: grid; gap: 0.5rem; }
.card { border: 1px solid #ddd; border-radius: 8px; padding: 0.6rem 1rem; }
.meta { color: #666; font-size: 0.9rem; margin-left: 8px; }
.error { color: #b00020; }
</style>

// SkyScout/frontend/src/App.tsx
import { useState } from "react";
import { searchFlights, API_URL, type FlightOption } from "./api";

export function App() {
  const [origin, setOrigin] = useState("JFK");
  const [destination, setDestination] = useState("LHR");
  const [results, setResults] = useState<FlightOption[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function onSearch(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      setResults(await searchFlights(origin, destination));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main style={styles.page}>
      <h1>✈️ SkyScout</h1>
      <p style={styles.sub}>Scout the skies for flights — talks only to its own backend at <code>{API_URL}</code></p>

      <form onSubmit={onSearch} style={styles.form}>
        <label>
          Origin
          <input value={origin} onChange={(e) => setOrigin(e.target.value)} placeholder="JFK" />
        </label>
        <label>
          Destination
          <input value={destination} onChange={(e) => setDestination(e.target.value)} placeholder="LHR" />
        </label>
        <button type="submit" disabled={loading}>{loading ? "Searching…" : "Search flights"}</button>
      </form>

      {error && <p style={styles.error}>Error: {error}</p>}

      <ul style={styles.list}>
        {results.map((f) => (
          <li key={f.flightId} style={styles.card}>
            <strong>{f.airline}</strong> — {f.origin} → {f.destination}
            <div style={styles.meta}>
              {new Date(f.departureTime).toLocaleString()} → {new Date(f.arrivalTime).toLocaleString()}
            </div>
            <div style={styles.meta}>
              {f.stops === 0 ? "Direct" : `${f.stops} stop(s)`} · <strong>${f.price.toFixed(2)}</strong>
            </div>
          </li>
        ))}
      </ul>
      {!loading && !error && results.length === 0 && <p>No flights yet — run a search.</p>}
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: { fontFamily: "system-ui, sans-serif", maxWidth: 640, margin: "2rem auto", padding: "0 1rem" },
  sub: { color: "#555" },
  form: { display: "flex", gap: "0.75rem", alignItems: "flex-end", flexWrap: "wrap", margin: "1.25rem 0" },
  list: { listStyle: "none", padding: 0, display: "grid", gap: "0.75rem" },
  card: { border: "1px solid #ddd", borderRadius: 8, padding: "0.75rem 1rem" },
  meta: { color: "#666", fontSize: "0.9rem", marginTop: 4 },
  error: { color: "#b00020" },
};
