// Weathervane/frontend/src/components/common/Pagination.vue
<script setup lang="ts">
import { ChevronLeft, ChevronRight } from "lucide-vue-next";
import { computed } from "vue";

import { Button } from "@/components/ui";
import type { PaginationMeta } from "@/lib/api/models";

const props = defineProps<{ meta: PaginationMeta }>();
const emit = defineEmits<{ "update:page": [page: number] }>();

const canPrev = computed(() => props.meta.page > 1);
const canNext = computed(() => props.meta.page < props.meta.totalPages);
</script>

<template>
  <nav class="flex items-center justify-between gap-4" aria-label="Pagination">
    <p class="text-sm text-muted-foreground">
      Page {{ meta.page }} of {{ meta.totalPages }} · {{ meta.total }} results
    </p>
    <div class="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        :disabled="!canPrev"
        aria-label="Previous page"
        @click="emit('update:page', meta.page - 1)"
      >
        <ChevronLeft class="h-4 w-4" />
        Prev
      </Button>
      <Button
        variant="outline"
        size="sm"
        :disabled="!canNext"
        aria-label="Next page"
        @click="emit('update:page', meta.page + 1)"
      >
        Next
        <ChevronRight class="h-4 w-4" />
      </Button>
    </div>
  </nav>
</template>

// SkyScout/frontend/src/components/common/Pagination.tsx
import { ChevronLeft, ChevronRight } from "lucide-react";

import { Button } from "@/components/ui/button";
import type { PaginationMeta } from "@/types/app";

interface PaginationProps {
  meta: PaginationMeta;
  onPageChange: (page: number) => void;
}

export function Pagination({ meta, onPageChange }: PaginationProps) {
  const { page, totalPages, total, pageSize } = meta;
  if (totalPages <= 1) return null;

  const from = total === 0 ? 0 : (page - 1) * pageSize + 1;
  const to = Math.min(page * pageSize, total);

  return (
    <nav className="flex items-center justify-between gap-4 pt-4" aria-label="Pagination">
      <p className="text-sm text-muted-foreground">
        Showing <span className="font-medium text-foreground">{from}</span>–
        <span className="font-medium text-foreground">{to}</span> of{" "}
        <span className="font-medium text-foreground">{total}</span>
      </p>
      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => onPageChange(page - 1)}
          disabled={page <= 1}
          aria-label="Previous page"
        >
          <ChevronLeft className="h-4 w-4" />
          Prev
        </Button>
        <span className="text-sm tabular-nums">
          {page} / {totalPages}
        </span>
        <Button
          variant="outline"
          size="sm"
          onClick={() => onPageChange(page + 1)}
          disabled={page >= totalPages}
          aria-label="Next page"
        >
          Next
          <ChevronRight className="h-4 w-4" />
        </Button>
      </div>
    </nav>
  );
}
