// SkyScout/frontend/src/components/common/EmptyState.tsx
import type { LucideIcon } from "lucide-react";
import { Inbox } from "lucide-react";
import type { ReactNode } from "react";

import { cn } from "@/lib/utils";

interface EmptyStateProps {
  icon?: LucideIcon;
  title: string;
  description?: string;
  action?: ReactNode;
  className?: string;
}

export function EmptyState({ icon: Icon = Inbox, title, description, action, className }: EmptyStateProps) {
  return (
    <div
      className={cn(
        "flex flex-col items-center justify-center rounded-lg border border-dashed p-10 text-center",
        className,
      )}
    >
      <Icon className="mb-4 h-10 w-10 text-muted-foreground" aria-hidden />
      <h3 className="text-base font-semibold">{title}</h3>
      {description && <p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// PennyPilot/frontend/src/lib/components/common/EmptyState.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import Card from '$lib/components/ui/Card.svelte';

  interface Props {
    title: string;
    description?: string;
    icon?: Snippet;
    action?: Snippet;
  }

  let { title, description, icon, action }: Props = $props();
</script>

<Card class="flex flex-col items-center justify-center gap-3 p-12 text-center">
  {#if icon}
    <div class="rounded-full bg-muted p-3 text-muted-foreground">{@render icon()}</div>
  {/if}
  <div class="space-y-1">
    <h3 class="text-base font-semibold">{title}</h3>
    {#if description}<p class="mx-auto max-w-sm text-sm text-muted-foreground">{description}</p>{/if}
  </div>
  {#if action}{@render action()}{/if}
</Card>
