// SkyScout/frontend/src/components/common/ErrorState.tsx
import { AlertTriangle } from "lucide-react";

import { Button } from "@/components/ui/button";
import { ApiError } from "@/lib/ApiError";
import { cn } from "@/lib/utils";

interface ErrorStateProps {
  error?: unknown;
  title?: string;
  onRetry?: () => void;
  className?: string;
}

function messageFor(error: unknown): string {
  if (error instanceof ApiError) return error.message;
  if (error instanceof Error) return error.message;
  return "Something went wrong. Please try again.";
}

export function ErrorState({ error, title = "Something went wrong", onRetry, className }: ErrorStateProps) {
  const requestId = error instanceof ApiError ? error.requestId : undefined;
  return (
    <div
      role="alert"
      className={cn(
        "flex flex-col items-center justify-center rounded-lg border border-destructive/30 bg-destructive/5 p-10 text-center",
        className,
      )}
    >
      <AlertTriangle className="mb-4 h-10 w-10 text-destructive" aria-hidden />
      <h3 className="text-base font-semibold">{title}</h3>
      <p className="mt-1 max-w-sm text-sm text-muted-foreground">{messageFor(error)}</p>
      {requestId && <p className="mt-1 text-xs text-muted-foreground/70">Reference: {requestId}</p>}
      {onRetry && (
        <Button variant="outline" className="mt-4" onClick={onRetry}>
          Try again
        </Button>
      )}
    </div>
  );
}

// PennyPilot/frontend/src/lib/components/common/ErrorState.svelte
<script lang="ts">
  import { TriangleAlert } from '@lucide/svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import { ApiError } from '$lib/api/ApiError';

  interface Props {
    error?: unknown;
    onRetry?: () => void;
    title?: string;
  }

  let { error, onRetry, title = 'Something went wrong' }: Props = $props();

  const message = $derived(
    error instanceof ApiError ? error.message : 'An unexpected error occurred. Please try again.'
  );
  const requestId = $derived(error instanceof ApiError ? error.requestId : undefined);
</script>

<Card class="flex flex-col items-center gap-3 p-12 text-center">
  <div class="rounded-full bg-destructive/10 p-3 text-destructive">
    <TriangleAlert class="h-6 w-6" />
  </div>
  <div class="space-y-1">
    <h3 class="text-base font-semibold">{title}</h3>
    <p class="mx-auto max-w-sm text-sm text-muted-foreground">{message}</p>
    {#if requestId}<p class="text-xs text-muted-foreground/70">Request ID: {requestId}</p>{/if}
  </div>
  {#if onRetry}<Button variant="outline" onclick={onRetry}>Try again</Button>{/if}
</Card>
