// TripWeaver/frontend/src/components/common/Pagination.tsx
import { Show } from 'solid-js';
import { ChevronLeft, ChevronRight } from 'lucide-solid';
import { Button } from '@/components/ui/Button';
import type { PageMeta } from '@/lib/api/models';

export function Pagination(props: { meta: PageMeta; onPage: (page: number) => void }) {
  return (
    <Show when={props.meta.totalPages > 1}>
      <div class="mt-4 flex items-center justify-between text-sm text-slate-600">
        <span>
          Page {props.meta.page} of {props.meta.totalPages} · {props.meta.total} total
        </span>
        <div class="flex gap-2">
          <Button
            variant="secondary"
            size="sm"
            disabled={props.meta.page <= 1}
            onClick={() => props.onPage(props.meta.page - 1)}
          >
            <ChevronLeft size={16} aria-hidden="true" /> Prev
          </Button>
          <Button
            variant="secondary"
            size="sm"
            disabled={props.meta.page >= props.meta.totalPages}
            onClick={() => props.onPage(props.meta.page + 1)}
          >
            Next <ChevronRight size={16} aria-hidden="true" />
          </Button>
        </div>
      </div>
    </Show>
  );
}

// PennyPilot/frontend/src/lib/components/common/Pagination.svelte
<script lang="ts">
  import { ChevronLeft, ChevronRight } from '@lucide/svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import type { PaginationMeta } from '$lib/api/models';

  interface Props {
    meta: PaginationMeta;
    onPage: (page: number) => void;
  }

  let { meta, onPage }: Props = $props();
</script>

{#if meta.totalPages > 1}
  <div class="flex items-center justify-between gap-4 text-sm">
    <p class="text-muted-foreground">
      Page {meta.page} of {meta.totalPages} · {meta.total} total
    </p>
    <div class="flex gap-2">
      <Button variant="outline" size="sm" disabled={meta.page <= 1} onclick={() => onPage(meta.page - 1)}>
        <ChevronLeft class="h-4 w-4" /> Prev
      </Button>
      <Button
        variant="outline"
        size="sm"
        disabled={meta.page >= meta.totalPages}
        onclick={() => onPage(meta.page + 1)}
      >
        Next <ChevronRight class="h-4 w-4" />
      </Button>
    </div>
  </div>
{/if}
