// Weathervane/frontend/src/App.vue
<script setup>
import { ref } from "vue";
import { API_URL, getForecast } from "./api.js";

const city = ref("London");
const days = ref(5);
const results = ref([]);
const error = ref(null);
const loading = ref(false);

async function search() {
  loading.value = true;
  error.value = null;
  try {
    results.value = await getForecast(city.value, Number(days.value));
  } catch (e) {
    error.value = e.message;
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <main>
    <h1>🌤️ Weathervane</h1>
    <p class="sub">See the forecast for your trip — talks only to its own backend at <code>{{ API_URL }}</code></p>

    <form @submit.prevent="search">
      <label>City <input v-model="city" placeholder="London" /></label>
      <label>Days <input v-model="days" type="number" min="1" max="5" style="width:70px" /></label>
      <button type="submit" :disabled="loading">{{ loading ? "Loading…" : "Get forecast" }}</button>
    </form>

    <p v-if="error" class="error">Error: {{ error }}</p>

    <ul>
      <li v-for="d in results" :key="d.date" class="card">
        <strong>{{ d.date }}</strong> — {{ d.condition }}
        <span class="meta">high {{ d.high }}°C · low {{ d.low }}°C</span>
      </li>
    </ul>
    <p v-if="!loading && !error && results.length === 0">No forecast yet — run a search.</p>
  </main>
</template>

<style scoped>
main { font-family: system-ui, sans-serif; max-width: 560px; margin: 2rem auto; padding: 0 1rem; }
.sub { color: #555; }
form { display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; margin: 1rem 0; }
ul { list-style: none; padding: 0; display: grid; gap: 0.5rem; }
.card { border: 1px solid #ddd; border-radius: 8px; padding: 0.6rem 1rem; }
.meta { color: #666; font-size: 0.9rem; margin-left: 8px; }
.error { color: #b00020; }
</style>

// Roost/frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HotelService, HotelOption } from './hotel.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <main style="max-width:640px;margin:2rem auto;padding:0 1rem;">
      <h1>🏨 Roost</h1>
      <p style="color:#555">Find a place to stay — talks only to its own backend at <code>{{ api }}</code></p>

      <form (ngSubmit)="search()" style="display:flex;gap:.75rem;align-items:flex-end;flex-wrap:wrap;margin:1.25rem 0;">
        <label>City<br /><input [(ngModel)]="city" name="city" placeholder="London" /></label>
        <label>Nights<br /><input [(ngModel)]="nights" name="nights" type="number" min="1" style="width:80px" /></label>
        <button type="submit" [disabled]="loading">{{ loading ? 'Searching…' : 'Search hotels' }}</button>
      </form>

      <p *ngIf="error" style="color:#b00020">Error: {{ error }}</p>

      <ul style="list-style:none;padding:0;display:grid;gap:.75rem;">
        <li *ngFor="let h of results" style="border:1px solid #ddd;border-radius:8px;padding:.75rem 1rem;">
          <strong>{{ h.name }}</strong> — {{ '★'.repeat(h.starRating) }}
          <div style="color:#666;font-size:.9rem;margin-top:4px;">
            \${{ h.pricePerNight.toFixed(2) }}/night · total <strong>\${{ h.totalPrice.toFixed(2) }}</strong>
          </div>
          <div style="color:#666;font-size:.9rem;">{{ h.amenities.join(' · ') }}</div>
        </li>
      </ul>
      <p *ngIf="!loading && !error && results.length === 0">No hotels yet — run a search.</p>
    </main>
  `,
})
export class AppComponent {
  city = 'London';
  nights = 3;
  results: HotelOption[] = [];
  error: string | null = null;
  loading = false;
  readonly api: string;

  constructor(private hotels: HotelService) {
    this.api = hotels.apiUrl;
  }

  search() {
    this.loading = true;
    this.error = null;
    this.hotels.searchHotels(this.city, this.nights).subscribe({
      next: (r) => { this.results = r; this.loading = false; },
      error: (e) => { this.error = e.message ?? 'request failed'; this.loading = false; },
    });
  }
}
