// Weathervane/frontend/src/components/ui/Label.vue
<script setup lang="ts">
import { Label } from "reka-ui";
import type { HTMLAttributes } from "vue";

import { cn } from "@/lib/utils/cn";

const props = defineProps<{ for?: string; class?: HTMLAttributes["class"] }>();
</script>

<template>
  <Label
    :for="props.for"
    :class="
      cn(
        'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        props.class,
      )
    "
  >
    <slot />
  </Label>
</template>

// PennyPilot/frontend/src/lib/components/ui/Label.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLLabelAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils/cn';

  interface Props extends Omit<HTMLLabelAttributes, 'class'> {
    class?: string;
    children?: Snippet;
  }

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<label
  class={cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', className)}
  {...rest}
>
  {@render children?.()}
</label>
