// PennyPilot/frontend/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';

  type Variant = 'default' | 'secondary' | 'outline' | 'success' | 'warning' | 'destructive';

  interface Props {
    variant?: Variant;
    class?: string;
    children?: Snippet;
  }

  let { variant = 'default', class: className = '', children }: Props = $props();

  const variants: Record<Variant, string> = {
    default: 'border-transparent bg-primary/10 text-primary',
    secondary: 'border-transparent bg-secondary text-secondary-foreground',
    outline: 'text-foreground',
    success: 'border-transparent bg-success/15 text-success',
    warning: 'border-transparent bg-warning/15 text-warning',
    destructive: 'border-transparent bg-destructive/10 text-destructive'
  };
</script>

<span
  class={cn(
    'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium',
    variants[variant],
    className
  )}
>
  {@render children?.()}
</span>

// TripWeaver/frontend/src/components/ui/Badge.tsx
import { splitProps, type JSX } from 'solid-js';

type Tone = 'neutral' | 'success' | 'warning' | 'danger' | 'info';

const TONES: Record<Tone, string> = {
  neutral: 'bg-slate-100 text-slate-700',
  success: 'bg-green-100 text-green-800',
  warning: 'bg-amber-100 text-amber-800',
  danger: 'bg-red-100 text-red-800',
  info: 'bg-brand-100 text-brand-700',
};

export function Badge(props: JSX.HTMLAttributes<HTMLSpanElement> & { tone?: Tone }) {
  const [local, rest] = splitProps(props, ['tone', 'class', 'children']);
  return (
    <span
      {...rest}
      class={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${TONES[local.tone ?? 'neutral']} ${local.class ?? ''}`}
    >
      {local.children}
    </span>
  );
}
