// PennyPilot/frontend/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes, HTMLAnchorAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils/cn';

  type Variant = 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link';
  type Size = 'sm' | 'md' | 'lg' | 'icon';

  interface Props extends Omit<HTMLButtonAttributes & HTMLAnchorAttributes, 'class'> {
    variant?: Variant;
    size?: Size;
    loading?: boolean;
    href?: string;
    class?: string;
    children?: Snippet;
  }

  let {
    variant = 'default',
    size = 'md',
    loading = false,
    href,
    class: className = '',
    disabled = false,
    type = 'button',
    children,
    ...rest
  }: Props = $props();

  const variants: Record<Variant, string> = {
    default: 'bg-primary text-primary-foreground hover:bg-primary/90',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
    outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
    ghost: 'hover:bg-accent hover:text-accent-foreground',
    destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
    link: 'text-primary underline-offset-4 hover:underline'
  };

  const sizes: Record<Size, string> = {
    sm: 'h-9 px-3 text-sm',
    md: 'h-10 px-4 text-sm',
    lg: 'h-11 px-6 text-base',
    icon: 'h-10 w-10'
  };
</script>

{#snippet inner()}
  {#if loading}
    <span
      class="inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent"
      aria-hidden="true"
    ></span>
  {/if}
  {@render children?.()}
{/snippet}

{#if href}
  <a
    {href}
    class={cn(
      'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
      variants[variant],
      sizes[size],
      className
    )}
    {...rest}
  >
    {@render inner()}
  </a>
{:else}
  <button
    {type}
    disabled={disabled || loading}
    class={cn(
      'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
      variants[variant],
      sizes[size],
      className
    )}
    {...rest}
  >
    {@render inner()}
  </button>
{/if}

// TripWeaver/frontend/src/components/ui/Button.tsx
import { splitProps, type JSX } from 'solid-js';

type Variant = 'primary' | 'secondary' | 'ghost' | 'danger';
type Size = 'sm' | 'md';

export type ButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: Variant;
  size?: Size;
};

const VARIANTS: Record<Variant, string> = {
  primary: 'bg-brand-600 text-white hover:bg-brand-700 disabled:bg-brand-300',
  secondary: 'border border-slate-300 bg-white text-slate-800 hover:bg-slate-50',
  ghost: 'text-slate-700 hover:bg-slate-100',
  danger: 'bg-over text-white hover:bg-red-700 disabled:bg-red-300',
};

const SIZES: Record<Size, string> = {
  sm: 'h-8 px-3 text-sm',
  md: 'h-10 px-4 text-sm',
};

export function Button(props: ButtonProps) {
  const [local, rest] = splitProps(props, ['variant', 'size', 'class', 'children']);
  return (
    <button
      type="button"
      {...rest}
      class={`inline-flex items-center justify-center gap-2 rounded-md font-medium transition-colors
        focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500
        disabled:cursor-not-allowed ${VARIANTS[local.variant ?? 'primary']} ${SIZES[local.size ?? 'md']} ${local.class ?? ''}`}
    >
      {local.children}
    </button>
  );
}
