// PennyPilot/frontend/src/lib/components/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils/cn';

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
    class?: string;
    children?: Snippet;
  }

  let { class: className = '', children, ...rest }: Props = $props();
</script>

<div class={cn('rounded-lg border bg-card text-card-foreground shadow-sm', className)} {...rest}>
  {@render children?.()}
</div>

// TripWeaver/frontend/src/components/ui/Card.tsx
import { splitProps, type JSX } from 'solid-js';

export function Card(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ['class', 'children']);
  return (
    <div {...rest} class={`rounded-xl border border-slate-200 bg-white shadow-sm ${local.class ?? ''}`}>
      {local.children}
    </div>
  );
}
