// TripWeaver/frontend/src/features/auth/components/AuthForm.tsx
import { Show } from 'solid-js';
import { createForm, zodForm } from '@modular-forms/solid';
import { useNavigate, useSearchParams } from '@solidjs/router';
import { TextField } from '@/components/ui/TextField';
import { Button } from '@/components/ui/Button';
import { Spinner } from '@/components/ui/Spinner';
import { applyApiError } from '@/lib/api/apply-api-error';
import { LoginSchema, RegisterSchema, type LoginForm } from '../schemas';
import { useLogin, useRegister } from '../mutations';

export function AuthForm(props: { mode: 'login' | 'register' }) {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const [form, { Form, Field }] = createForm<LoginForm>({
    // eslint-disable-next-line solid/reactivity -- mode is fixed per mounted route
    validate: zodForm(props.mode === 'login' ? LoginSchema : RegisterSchema),
  });
  const login = useLogin();
  const register = useRegister();

  const handleSubmit = async (values: LoginForm) => {
    try {
      if (props.mode === 'login') {
        await login.mutateAsync(values);
      } else {
        await register.mutateAsync(values);
      }
      const returnTo = typeof params.returnTo === 'string' ? params.returnTo : '/itineraries';
      navigate(returnTo, { replace: true });
    } catch (error) {
      applyApiError(form, error);
    }
  };

  return (
    <Form onSubmit={handleSubmit} class="flex flex-col gap-4">
      <Field name="email">
        {(field, fieldProps) => (
          <TextField
            {...fieldProps}
            type="email"
            label="Email"
            placeholder="you@example.com"
            autocomplete="email"
            value={field.value}
            error={field.error}
          />
        )}
      </Field>
      <Field name="password">
        {(field, fieldProps) => (
          <TextField
            {...fieldProps}
            type="password"
            label="Password"
            autocomplete={props.mode === 'login' ? 'current-password' : 'new-password'}
            value={field.value}
            error={field.error}
          />
        )}
      </Field>
      <Button type="submit" disabled={form.submitting} class="mt-2">
        <Show when={form.submitting}>
          <Spinner />
        </Show>
        {props.mode === 'login' ? 'Sign in' : 'Create account'}
      </Button>
    </Form>
  );
}

// SkyScout/frontend/src/features/auth/components/AuthForm.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useNavigate, useSearchParams } from "react-router-dom";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { applyApiError } from "@/lib/applyApiError";

import { loginSchema, registerSchema } from "../schemas";
import { useLogin, useRegister } from "../mutations";

interface AuthFormProps {
  mode: "login" | "register";
}

interface FormValues {
  email: string;
  password: string;
}

export function AuthForm({ mode }: AuthFormProps) {
  const isLogin = mode === "login";
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const returnTo = params.get("returnTo") || "/flights";

  const loginMutation = useLogin();
  const registerMutation = useRegister();
  const mutation = isLogin ? loginMutation : registerMutation;

  const form = useForm<FormValues>({
    resolver: zodResolver(isLogin ? loginSchema : registerSchema),
    defaultValues: { email: "", password: "" },
  });

  const onSubmit = form.handleSubmit((values) => {
    mutation.mutate(values, {
      onSuccess: () => {
        toast.success(isLogin ? "Welcome back!" : "Account created.");
        navigate(returnTo, { replace: true });
      },
      onError: (error) => applyApiError<FormValues>(error, form.setError),
    });
  });

  return (
    <Form {...form}>
      <form onSubmit={onSubmit} className="space-y-4" noValidate>
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Email</FormLabel>
              <FormControl>
                <Input
                  type="email"
                  autoComplete="email"
                  placeholder="you@example.com"
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="password"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Password</FormLabel>
              <FormControl>
                <Input
                  type="password"
                  autoComplete={isLogin ? "current-password" : "new-password"}
                  placeholder={isLogin ? "Your password" : "At least 8 characters"}
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit" className="w-full" loading={mutation.isPending}>
          {isLogin ? "Sign in" : "Create account"}
        </Button>
      </form>
    </Form>
  );
}
