// Weathervane/frontend/src/components/common/ErrorState.vue
<script setup lang="ts">
import { TriangleAlert } from "lucide-vue-next";
import { computed } from "vue";

import { Button } from "@/components/ui";
import { ApiError } from "@/lib/api/ApiError";

const props = defineProps<{ error?: unknown; title?: string; retryable?: boolean }>();
const emit = defineEmits<{ retry: [] }>();

const message = computed(() => {
  if (props.error instanceof ApiError) return props.error.message;
  if (props.error instanceof Error) return props.error.message;
  return "Something went wrong. Please try again.";
});

const requestId = computed(() =>
  props.error instanceof ApiError ? props.error.requestId : undefined,
);
</script>

<template>
  <div
    role="alert"
    class="flex flex-col items-center justify-center gap-3 rounded-xl border border-destructive/40 bg-destructive/5 p-8 text-center"
  >
    <TriangleAlert class="h-8 w-8 text-destructive" aria-hidden="true" />
    <div class="space-y-1">
      <p class="font-medium">{{ props.title ?? "Couldn't load this" }}</p>
      <p class="text-sm text-muted-foreground">{{ message }}</p>
      <p v-if="requestId" class="text-xs text-muted-foreground/70">Request {{ requestId }}</p>
    </div>
    <Button v-if="props.retryable !== false" variant="outline" size="sm" @click="emit('retry')">
      Try again
    </Button>
  </div>
</template>

// Roost/frontend/src/app/shared/components/error-state.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

import { ApiError } from '@core/error/api-error';

@Component({
  selector: 'app-error-state',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatIconModule, MatButtonModule],
  template: `
    <div
      role="alert"
      class="flex flex-col items-center justify-center gap-3 rounded-xl border border-red-300 bg-red-50 p-8 text-center"
    >
      <mat-icon class="text-red-600" aria-hidden="true">error_outline</mat-icon>
      <div class="space-y-1">
        <p class="font-medium">{{ title() }}</p>
        <p class="text-sm opacity-70">{{ message() }}</p>
      </div>
      @if (retryable()) {
        <button mat-stroked-button (click)="retry.emit()">Try again</button>
      }
    </div>
  `,
})
export class ErrorStateComponent {
  readonly error = input<unknown>();
  readonly title = input('Something went wrong');
  readonly retryable = input(true);
  readonly retry = output<void>();

  readonly message = computed(() => {
    const e = this.error();
    if (e instanceof ApiError) return e.message;
    if (e instanceof Error) return e.message;
    return 'Please try again.';
  });
}
